config/routes.rb
Rails.application.routes.draw do
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/index'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to action: "index", notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :title, :description, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
	def event_date(event)
		event.date.strftime("%m/%d/%Y at %I:%M%p")
	end
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :name, id: :event_title %>
  </div>
  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, id: :event_date %>
  </div>
  <div class="field">
    <%= form.label :number_of_volunteers %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :event_description %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Opportunities</h1>

  <div class="list-group">
  <% @events.each do |event| %>
    <div class="list-group-item list-group-item-action flex-column align-items-start">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><%= link_to event.name, event %></h5>
        <small><%= event_date(event) %></small>
      </div>
      <p><%= event.description %></p>
    </div>
  <% end %>
  </div>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<medium class="float-right"><%= event_date(@event) %></medium>
<h1><%= @event.name %></h1>

<p>
  <%= @event.description %>
</p>
<!-- scripts and style -->

<!-- /*<style>
#subject{
  float: left;
}
#phone{
  float: left;
}

</style>*/ -->
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  Sign Up!
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Email</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="" method="post">
          <label for="POST-name">lupita@gmail.com</label><br>
          <label for="POST-name">PhD student, looking for volunteers to take part in a Bitcoin user survey.</label><br>
          <label for="POST-name">Hi Lupita, I would love to help out! You may reach me at this email.<br> Thank you!</label><br>
          <!-- <form id="subject" type="text" name="Subject">
          <form id="phone" type="text" name="Phone number"> -->
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send Email</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>immiGiving</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<!-- <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="#">immiGiving</a>
    </nav> -->

    <!-- scripts and style -->

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <style>
    body {
        font: 400 15px Lato, sans-serif;
        line-height: 1.8;
        color: #818181;
    }
    h2 {
        font-size: 24px;
        text-transform: uppercase;
        color: #303030;
        font-weight: 600;
        margin-bottom: 30px;
    }
    h4 {
        font-size: 19px;
        line-height: 1.375em;
        color: #303030;
        font-weight: 400;
        margin-bottom: 30px;
    }
    .jumbotron {
      background-color: #669999 ;
      color: #fff;
      padding: 100px 25px;
      font-family: Montserrat, sans-serif;
    }
    .container-fluid {
        padding: 60px 50px;
    }
    .bg-grey {
        background-color: #e1eaea;
    }
    .logo-small {
        color: #669999;
        font-size: 50px;
    }
    .logo {
      color: #669999 ;
      font-size: 150px;
    }
    .thumbnail {
        padding: 0 0 15px 0;
        border: none;
        border-radius: 0;
    }
    .thumbnail img {
        width: 100%;
        height: 100%;
        margin-bottom: 10px;
    }
    .carousel-inner img {
    width: 100%; /* Set width to 100% */
    margin: auto;
}
.carousel-caption h3 {
    color: #fff !important;
}
    .carousel-control.right, .carousel-control.left {
        background-image: none;
        color: #996666;
    }
    .carousel-indicators li {
        border-color: #669999;
    }
    .carousel-indicators li.active {
        background-color: #996666;
    }
    .item h4 {
        font-size: 19px;
        line-height: 1.375em;
        font-weight: 400;
        font-style: italic;
        margin: 70px 0;
    }
    .item span {
        font-style: normal;
    }
    .panel {
        border: 1px solid #669999;
        border-radius:0 !important;
        transition: box-shadow 0.5s;
    }
    .panel:hover {
        box-shadow: 5px 0px 40px rgba(0,0,0, .2);
    }
    .panel-footer .btn:hover {
        border: 1px solid #669999;
        background-color: #fff !important;
        color: #669999;
    }
    .panel-heading {
        color: #fff !important;
        background-color: #669999 !important;
        padding: 25px;
        border-bottom: 1px solid transparent;
        border-top-left-radius: 0px;
        border-top-right-radius: 0px;
        border-bottom-left-radius: 0px;
        border-bottom-right-radius: 0px;
    }
    .panel-footer {
        background-color: white !important;
    }
    .panel-footer h3 {
        font-size: 32px;
    }
    .panel-footer h4 {
        color: #aaa;
        font-size: 14px;
    }
    .panel-footer .btn {
        margin: 15px 0;
        background-color: #;
        color: #fff;
    }
    .navbar {
        margin-bottom: 0;
        background-color: #669999;
        z-index: 9999;
        border: 0;
        font-size: 12px !important;
        line-height: 1.42857143 !important;
        letter-spacing: 4px;
        border-radius: 0;
        font-family: Montserrat, sans-serif;
    }
    .navbar li a, .navbar .navbar-brand {
        color: #fff !important;
    }
    .navbar-nav li a:hover, .navbar-nav li.active a {
        color: #996666 !important;
        background-color: #fff !important;
    }
    .navbar-default .navbar-toggle {
        border-color: transparent;
        color: #fff !important;
    }
    footer .glyphicon {
        font-size: 20px;
        margin-bottom: 20px;
        color: #996666;
    }
    .slideanim {visibility:hidden;}
    .slide {
        animation-name: slide;
        -webkit-animation-name: slide;
        animation-duration: 1s;
        -webkit-animation-duration: 1s;
        visibility: visible;
    }
    @keyframes slide {
      0% {
        opacity: 0;
        transform: translateY(70%);
      }
      100% {
        opacity: 1;
        transform: translateY(0%);
      }
    }
    @-webkit-keyframes slide {
      0% {
        opacity: 0;
        -webkit-transform: translateY(70%);
      }
      100% {
        opacity: 1;
        -webkit-transform: translateY(0%);
      }
    }
    @media screen and (max-width: 768px) {
      .col-sm-4 {
        text-align: center;
        margin: 25px 0;
      }
      .btn-lg {
          width: 100%;
          margin-bottom: 35px;
      }
    }
    @media screen and (max-width: 480px) {
      .logo {
          font-size: 150px;
      }
    }
    </style>

</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">

  <nav class="navbar navbar-default navbar-fixed-top" style="padding-bottom: 0px; padding-top: 0px">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Expectations</a></li>
        </ul>
      </div>
    </div>
  </nav>

<div class="jumbotron text-center">
  <h1>immiGiving</h1>
  <p>Connect Take Action Grow</p>
</div>

    <!-- about us -->

    <div id="about" class="container-fluid ">
  <br><br>
  <div class="row">
    <div class="col-sm-8 bg-grey">
      <h2>About Us</h2><br>
      <p>immiGiving offers an accessible way for individuals from all walks of life to get involved with the immigrant rights movement. We connect immigrant rights leaders to potential volunteers, and in doing so, expand leadership and skill development. Our aim is to build capacity and nurture lasting relationships to empower and strengthen the next generation of leaders.
        Our ultimate goal is to actively engage in and promote the growth of the immigrant rights movement!<br>In 2017, a group of undocumented individuals ventured on a journey collectively to reflect upon the narratives perpetuated in the media around human dignity. We recognize that undocumented individuals are worth more than their labor and productivity. immiGiving is a safe space for immigrant rights leaders and potential volunteers to take back their labor and redefine the immigrant narrative as one of community building and immigrant wellness.  ImmiGiving focuses on the small work that often goes unnoticed and gives them the human capital to turn an event into a movement.</p>
      <br>
      <!-- <button class="btn btn-default btn-lg">Get in Touch</button> -->
    </div>
    <div class="col-sm-3">
      <span class="glyphicon glyphicon-grain logo"></span>
    </div>
  </div><br>

  <!-- ruby part -->


    <div class="container">
    	<%= yield %>
    </div>
  </body>
</html>

<!-- leader volunteer description  -->
<br>
<div id="contact" class="container-fluid ">
  <br><br>
<div class="col-sm-3">
  <span class="glyphicon glyphicon-leaf logo"></span>
</div>
  <div class="col-sm-8 container-fluid bg-grey">
    <h2>Expectations</h2><br>
    <h4>Leaders: immiGiving acknowledges that the quest for immigrant rights justice is often married by a lack of helping hands. We want to give leaders, activists, and organizers the platform to enlist assistance on an individual event basis. Whether it be a protest, a panel, or even just a potluck, immiGiving does the outreach for you. As you interact with the immiGiving community we implore our help-seekers to develop skill improvement programs for their volunteers so that they grow within the immigrant rights movement and expand the effectiveness of the immigrant progress.</h4><br>
    <h4>Volunteers: The immigrant community faces many challenges in their daily lives, but they rise above them each time. immiGiving connects individuals who have so much to contribute to grassroots efforts that are working to push for immigrant rights and justice. Through these opportunities, we hope that volunteers make personal connections with other community members who can help develop their leadership skills and knowledge about immigrant right. The only requirement is to fulfill a commitment to its entirety.</h4>